# Generated by Django 5.2.4 on 2025-07-08 11:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodetype',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ticketstatus',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userroles',
            old_name='name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='projectnetworktype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectnetworktype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ticketentryactiontype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usstate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usstate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='macaddresslookup',
            name='mac_address',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='macaddresslookup',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meshcpeinstall',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nodetype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='nodetype',
            name='max_ports',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodetype',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodetype',
            name='subscriber_switch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscriberpaymentmethod',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='account_portal_visible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketentryaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='ticketentryaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticketentryactiontype',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketentryactiontype',
            name='description_past_tense',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketentryactiontype',
            name='display',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketentryactiontype',
            name='display_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketentryactiontype',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticketentryactiontype',
            name='identifier',
            field=models.CharField(default='default', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='knms_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='remember_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpermissioncategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='userpermissioncategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userroles',
            name='dispatch',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usstate',
            name='abbr',
            field=models.CharField(default='default', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='nodeclass',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='nodeframe',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='outage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='outagehomeseffected',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='portmacaddress',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectalert',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='statement',
            name='amount_past_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='statement',
            name='archived',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statement',
            name='final_statement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statement',
            name='initial_statement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statement',
            name='qbo_invoice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statementitem',
            name='custom',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberalert',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscriberalert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='subscriberemaillog',
            name='sent_to',
            field=models.CharField(default='', max_length=555),
        ),
        migrations.AlterField(
            model_name='subscriberemaillog',
            name='success',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscribersmslog',
            name='success',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='ticketentry',
            name='submitted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_company',
            field=models.ForeignKey(db_column='user_company_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.usercompany'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(db_column='user_role_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.userroles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_phone',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='userpermissiondefaults',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='userpermissionsubcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='userpermissiontype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
