# Generated by Django 5.2.1 on 2025-06-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMessageType',
            fields=[
                ('bulk_message_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bulk_message_type',
            },
        ),
    ]
