# Generated by Django 5.2.1 on 2025-06-03 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bulkmessagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEmailTemplate',
            fields=[
                ('bulk_email_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulk_message_type', models.ForeignKey(db_column='bulk_message_type_id', on_delete=django.db.models.deletion.CASCADE, to='app.bulkmessagetype')),
            ],
            options={
                'db_table': 'bulk_email_templates',
            },
        ),
    ]
