# Generated by Django 5.2.4 on 2025-07-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='node_port_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='acp_application_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='autopay_merchant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='home',
            field=models.ForeignKey(db_column='home_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.home'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='merchant_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='node',
            field=models.ForeignKey(db_column='node_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.node'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='primary_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='primary_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='qbo_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='service_plan',
            field=models.ForeignKey(db_column='service_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.serviceplan'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
