# Generated by Django 5.2.4 on 2025-07-22 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subscriber_node_port_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketentry',
            name='dispatch_appointment',
            field=models.OneToOneField(blank=True, db_column='dispatch_appointment_id', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_entry', to='app.dispatchappointment'),
        ),
        migrations.AlterField(
            model_name='dispatchappointment',
            name='ticket',
            field=models.ForeignKey(db_column='ticket_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_appointments', to='app.ticket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicechangeschedule',
            name='ticket_entry',
            field=models.OneToOneField(db_column='ticket_entry_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_change_schedule', to='app.ticketentry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='home',
            field=models.ForeignKey(db_column='home_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='app.home'),
        ),
    ]
