# Generated by Django 5.2.4 on 2025-07-22 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ticketentry_dispatch_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketentry',
            name='dispatch_appointment',
            field=models.OneToOneField(blank=True, db_column='dispatch_appointment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_entry', to='app.dispatchappointment'),
        ),
    ]
