# Generated by Django 5.2.4 on 2025-07-22 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_ticketentry_dispatch_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketentryaction',
            name='type',
            field=models.ForeignKey(blank=True, db_column='ticket_entry_action_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ticketentryactiontype'),
        ),
    ]
