# Generated by Django 5.2.4 on 2025-07-23 11:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_subscriber_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='portmacaddress',
            old_name='id',
            new_name='PortMacAddress_id',
        ),
        migrations.RemoveField(
            model_name='outage',
            name='effected_homes',
        ),
        migrations.AddField(
            model_name='macaddress',
            name='home',
            field=models.ForeignKey(blank=True, db_column='home_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mac_addresses', to='app.home'),
        ),
        migrations.AlterField(
            model_name='home',
            name='mac_address',
            field=models.OneToOneField(db_column='mac_address_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_home', to='app.macaddress'),
        ),
        migrations.AlterField(
            model_name='ont',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='ont',
            name='home',
            field=models.ForeignKey(db_column='home_id', on_delete=django.db.models.deletion.CASCADE, related_name='onts', to='app.home'),
        ),
        migrations.AlterField(
            model_name='ont',
            name='manufacturer',
            field=models.ForeignKey(db_column='ont_manufacturer_id', on_delete=django.db.models.deletion.PROTECT, related_name='onts', to='app.ontmanufacturer'),
        ),
        migrations.AlterField(
            model_name='ont',
            name='node',
            field=models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.PROTECT, related_name='onts', to='app.node'),
        ),
        migrations.AlterField(
            model_name='outage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='outage',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='outages', to='app.project'),
        ),
        migrations.AlterField(
            model_name='outagehomeseffected',
            name='outage',
            field=models.ForeignKey(db_column='outage_id', on_delete=django.db.models.deletion.CASCADE, related_name='effected', to='app.outage'),
        ),
        migrations.AlterField(
            model_name='portmacaddress',
            name='mac_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='portmacaddress',
            name='node',
            field=models.ForeignKey(blank=True, db_column='node_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_mac_addresses', to='app.node'),
        ),
        migrations.AlterField(
            model_name='portmacaddress',
            name='node_admin_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portmacaddress',
            name='node_oper_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portmacaddress',
            name='node_rate_down',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portmacaddress',
            name='node_rate_up',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portmacaddress',
            name='node_switch_module',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portmacaddress',
            name='node_switch_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
