# Generated by Django 5.2.4 on 2025-07-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_outage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='network_type',
            field=models.ForeignKey(blank=True, db_column='network_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.projectnetworktype'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='outage',
            field=models.ForeignKey(blank=True, db_column='outage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert', to='app.outage'),
        ),
        migrations.AlterField(
            model_name='servicechangeschedule',
            name='ticket_entry',
            field=models.ForeignKey(db_column='ticket_entry_id', on_delete=django.db.models.deletion.CASCADE, related_name='service_change_schedule', to='app.ticketentry'),
        ),
        migrations.RemoveField(
            model_name='ticketentryaction',
            name='ticket_entry',
        ),
        migrations.AddField(
            model_name='ticketentryaction',
            name='ticket_entry',
            field=models.ManyToManyField(db_column='ticket_entry_id', related_name='actions', to='app.ticketentry'),
        ),
    ]
